spring:
  application:
    name: securitydemo
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/auth_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update} # Production တွင် update ထက် validate / none ကို သုံးပါ
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # ===== Spring Mail Configuration (SMTP) =====
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000
    refresh-cookie-name: refreshToken
    cookie-secure: ${COOKIE_SECURE:false}
    cookie-samesite: ${COOKIE_SAMESITE:Lax}

google:
  client-id: ${GOOGLE_CLIENT_ID}